### ISSUE TITLE
java.lang.StackOverflowError: null

### ISSUE THREAD

**Issue by suin** [suin/php-scala-migration-example#1]
When make POST request on `localhost:9000/api/auth`,

```
http -v POST localhost:9000/api/auth username=alice password=secret
```

Then get errors:

```
2015-05-26 16:20:17,272 - [ERROR] - from akka.actor.ActorSystemImpl in play-akka.actor.default-dispatcher-3 
Uncaught error from thread [play-akka.actor.default-dispatcher-4] shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled
java.lang.StackOverflowError: null
    at controllers.AuthApi$.idTag(AuthApi.scala:10) ~[classes/:na]
    at controllers.ProprietaryAuthConfig$class.idTag(ProprietaryAuthConfig.scala:33) ~[classes/:na]
    at controllers.AuthApi$.idTag(AuthApi.scala:10) ~[classes/:na]
    at controllers.ProprietaryAuthConfig$class.idTag(ProprietaryAuthConfig.scala:33) ~[classes/:na]
    at controllers.AuthApi$.idTag(AuthApi.scala:10) ~[classes/:na]
    at controllers.ProprietaryAuthConfig$class.idTag(ProprietaryAuthConfig.scala:33) ~[classes/:na]
    at controllers.AuthApi$.idTag(AuthApi.scala:10) ~[classes/:na]
    at controllers.ProprietaryAuthConfig$class.idTag(ProprietaryAuthConfig.scala:33) ~[classes/:na]
    at controllers.AuthApi$.idTag(AuthApi.scala:10) ~[classes/:na]
    at controllers.ProprietaryAuthConfig$class.idTag(ProprietaryAuthConfig.scala:33) ~[classes/:na]
    at controllers.AuthApi$.idTag(AuthApi.scala:10) ~[classes/:na]
    at controllers.ProprietaryAuthConfig$class.idTag(ProprietaryAuthConfig.scala:33) ~[classes/:na]
    at controllers.AuthApi$.idTag(AuthApi.scala:10) ~[classes/:na]
    at controllers.ProprietaryAuthConfig$class.idTag(ProprietaryAuthConfig.scala:33) ~[classes/:na]
    at controllers.AuthApi$.idTag(AuthApi.scala:10) ~[classes/:na]
        ...
```

**Comment by suin** [comment]
Solved.
